// Каталог продуктов ИВП. Источник — раздел 5 брифа.
// Заводим все продукты со статусом [есть]; [в разработке] и [план] — карточками-заглушками.
// Для MVP в витрине показываем все со статусом ready + coming; planned остаются в резерве.

export type ProductType = "program" | "course" | "practicum" | "sampler" | "diy";
export type ProductStatus = "ready" | "coming" | "planned";
export type Track = "vocalist" | "psychologist" | "artist" | "school" | "mixed";
export type Core =
  | "entry" // Ядро 1. Вход в профессию
  | "pro" // Ядро 2. Состоявшийся профессионал
  | "master" // Ядро 3. Зрелый мастер
  | "b2b" // Ядро 4. Лидер команды
  | "cross"; // Межядерные форматы

export interface Program {
  id: string;
  slug: string;
  code?: string; // Номер программы из брифа
  title: string;
  short: string; // Короткое обещание
  type: ProductType;
  status: ProductStatus;
  core: Core;
  hours?: number;
  duration?: string;
  tracks: Track[];
  format?: string;
  price?: string;
  featured?: boolean;
}

export const typeLabels: Record<ProductType, string> = {
  program: "Программа ПК",
  course: "Мини-курс",
  practicum: "Практикум",
  sampler: "Бесплатный урок",
  diy: "Методический комплект",
};

export const coreLabels: Record<Core, string> = {
  entry: "Вход в профессию",
  pro: "Углубление практики",
  master: "Мастерство",
  b2b: "Для школ",
  cross: "Межядерные форматы",
};

export const trackLabels: Record<Track, string> = {
  vocalist: "Педагог по вокалу",
  psychologist: "Психолог",
  artist: "Артист-педагог",
  school: "Руководитель школы",
  mixed: "Смешанная аудитория",
};

export const statusLabels: Record<ProductStatus, string> = {
  ready: "Идёт набор",
  coming: "Скоро запустим",
  planned: "В разработке",
};

export const programs: Program[] = [
  // ─── Ядро 1. Вход в профессию ───
  {
    id: "p3",
    slug: "osnovy-vokalnoy-psihologii",
    code: "№3",
    title: "Основы вокальной психологии и психосоматики в педагогической деятельности",
    short:
      "Базовая программа для входа в специальность. Лицензированное удостоверение о повышении квалификации.",
    type: "program",
    status: "ready",
    core: "entry",
    hours: 72,
    duration: "3 месяца, онлайн",
    tracks: ["vocalist", "psychologist", "artist"],
    format: "Онлайн, лекции + практические сессии + супервизия",
    price: "от 48 000 ₽",
    featured: true,
  },
  {
    id: "e-diag",
    slug: "test-your-track",
    title: "Диагностический тест «Ваша траектория в вокальной психологии»",
    short: "15 вопросов, персональная рекомендация с чего начинать.",
    type: "sampler",
    status: "coming",
    core: "entry",
    tracks: ["vocalist", "psychologist", "artist"],
    price: "Бесплатно",
  },
  {
    id: "e-podcast",
    slug: "podcast-vp-who",
    title: "Мини-подкаст «Вокальный психолог: кто это и мой ли путь»",
    short: "5 эпизодов: три под каждый вход + два общих.",
    type: "sampler",
    status: "coming",
    core: "entry",
    tracks: ["vocalist", "psychologist", "artist"],
    price: "Бесплатно",
  },
  {
    id: "e-case",
    slug: "case-12-months",
    title: "Кейс-разбор: как педагог становится вокальным психологом за 12 месяцев",
    short: "Реальная траектория выпускника с цифрами и деталями.",
    type: "sampler",
    status: "coming",
    core: "entry",
    tracks: ["vocalist"],
    price: "Бесплатно",
  },

  // ─── Ядро 2. Состоявшийся профессионал: пробники ───
  {
    id: "p1",
    slug: "dyhanie-kotoroe-poyot",
    code: "№1",
    title: "«Дыхание, которое поёт»",
    short: "Психосоматика вокального дыхания — открытый мастер-класс.",
    type: "sampler",
    status: "ready",
    core: "pro",
    tracks: ["vocalist", "artist"],
    duration: "90 минут",
    price: "Бесплатно",
  },
  {
    id: "p10",
    slug: "govorit-s-uchenikom",
    code: "№10",
    title: "«Как говорить с учеником, чтобы он слушал»",
    short: "Психология педагогического общения — открытый разбор.",
    type: "sampler",
    status: "ready",
    core: "pro",
    tracks: ["vocalist", "artist"],
    duration: "60 минут",
    price: "Бесплатно",
  },
  {
    id: "p13",
    slug: "10-priznakov",
    code: "№13",
    title: "«10 признаков, что голос скоро сорвётся»",
    short: "Профилактика психосоматических нарушений голоса.",
    type: "sampler",
    status: "ready",
    core: "pro",
    tracks: ["vocalist"],
    duration: "45 минут",
    price: "Бесплатно",
  },
  {
    id: "p26",
    slug: "2-minuty-ubrat-zazhim",
    code: "№26",
    title: "«2 минуты, чтобы убрать зажим перед уроком»",
    short: "Расслабляющие и фокусирующие техники.",
    type: "sampler",
    status: "ready",
    core: "pro",
    tracks: ["vocalist", "artist"],
    duration: "30 минут",
    price: "Бесплатно",
  },

  // ─── Ядро 2. Мини-курсы ───
  {
    id: "p17",
    slug: "razvitie-eq",
    code: "№17",
    title: "Развитие эмоционального интеллекта в вокальном обучении",
    short: "Как считывать состояние ученика и работать с ним в моменте урока.",
    type: "course",
    status: "ready",
    core: "pro",
    hours: 16,
    duration: "2 недели",
    tracks: ["vocalist", "artist"],
    price: "12 000 ₽",
  },
  {
    id: "p12",
    slug: "motivaciya-plato",
    code: "№12",
    title: "Психология мотивации и преодоления творческого плато",
    short: "Что делать, когда ученик застрял и не растёт.",
    type: "course",
    status: "ready",
    core: "pro",
    hours: 16,
    duration: "2 недели",
    tracks: ["vocalist"],
    price: "12 000 ₽",
  },
  {
    id: "p22",
    slug: "skrytye-emocii",
    code: "№22",
    title: "Работа со скрытыми эмоциями в вокальном классе",
    short: "Что стоит за «не могу», «не хочу» и молчанием ученика.",
    type: "course",
    status: "ready",
    core: "pro",
    hours: 20,
    duration: "3 недели",
    tracks: ["vocalist", "psychologist"],
    price: "14 000 ₽",
  },
  {
    id: "p2",
    slug: "scenicheskoe-volnenie",
    code: "№2",
    title: "Преодоление сценического волнения",
    short: "Работа с телесной и когнитивной сторонами волнения.",
    type: "course",
    status: "ready",
    core: "pro",
    hours: 16,
    duration: "2 недели",
    tracks: ["vocalist", "artist"],
    price: "12 000 ₽",
  },
  {
    id: "p7",
    slug: "cifra-v-vokale",
    code: "№7",
    title: "Цифровые инструменты в работе педагога-вокалиста",
    short: "Практические инструменты для онлайн- и гибридной работы.",
    type: "course",
    status: "ready",
    core: "pro",
    hours: 12,
    duration: "10 дней",
    tracks: ["vocalist"],
    price: "9 000 ₽",
  },
  {
    id: "p25",
    slug: "podgotovka-k-kamere",
    code: "№25",
    title: "Психологическая подготовка к звукозаписи и выступлениям перед камерой",
    short: "Специфика поведения голоса вне живого зала.",
    type: "course",
    status: "ready",
    core: "pro",
    hours: 14,
    duration: "2 недели",
    tracks: ["vocalist", "artist"],
    price: "12 000 ₽",
  },

  // ─── Ядро 2. Практикумы с обратной связью ───
  {
    id: "p21",
    slug: "tvorcheskie-tehniki",
    code: "№21",
    title: "Творческие техники в вокальной педагогике",
    short: "10 дней практики с обратной связью — новые инструменты для урока.",
    type: "practicum",
    status: "ready",
    core: "pro",
    duration: "10 дней",
    tracks: ["vocalist"],
    price: "18 000 ₽",
  },
  {
    id: "p18",
    slug: "mak-diagnostika-blokov",
    code: "№18",
    title: "Применение МАК в диагностике вокальных блоков",
    short: "Метафорические ассоциативные карты в работе с состоянием ученика.",
    type: "practicum",
    status: "ready",
    core: "pro",
    duration: "10 дней",
    tracks: ["vocalist", "psychologist"],
    price: "18 000 ₽",
  },
  {
    id: "p14",
    slug: "sindrom-samozvantsa",
    code: "№14",
    title: "Психолого-педагогическое сопровождение ученика с синдромом самозванца",
    short: "Работа с феноменом на уровне урока и вне его.",
    type: "practicum",
    status: "ready",
    core: "pro",
    duration: "10 дней",
    tracks: ["vocalist", "psychologist"],
    price: "18 000 ₽",
  },
  {
    id: "p15",
    slug: "psihogigiena-golosa",
    code: "№15",
    title: "Психогигиена голоса и профилактика выгорания педагога",
    short: "Как сохранять ресурс, если работаешь много и с включённостью.",
    type: "practicum",
    status: "ready",
    core: "pro",
    duration: "10 дней",
    tracks: ["vocalist"],
    price: "18 000 ₽",
  },

  // ─── Ядро 2. Полные ПК (лицензированные) ───
  {
    id: "p5",
    slug: "vygoranie-i-ustojchivost",
    code: "№5",
    title: "Профилактика выгорания и формирование устойчивости",
    short: "Флагман линии для практикующих педагогов.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 72,
    duration: "3 месяца",
    tracks: ["vocalist", "artist"],
    format: "Онлайн + группы супервизии",
    price: "от 54 000 ₽",
    featured: true,
  },
  {
    id: "p16",
    slug: "travmaticheskie-patterny",
    code: "№16",
    title: "Педагогическая поддержка при травматичных паттернах в голосе",
    short: "Пограничные состояния — где заканчивается педагогика и куда направлять.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist", "psychologist"],
    price: "от 42 000 ₽",
  },
  {
    id: "p24",
    slug: "neyropsihologia-peniya",
    code: "№24",
    title: "Нейропсихология пения: от мозга к голосу",
    short: "Как когнитивные процессы устроены в голосовом акте.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist", "psychologist"],
    price: "от 42 000 ₽",
  },
  {
    id: "p9",
    slug: "somaticheskij-podhod",
    code: "№9",
    title: "Соматический подход и основы биомеханики голоса",
    short: "Тело как ключ к пониманию голоса.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist"],
    price: "от 42 000 ₽",
  },
  {
    id: "p27",
    slug: "integrativnye-metody",
    code: "№27",
    title: "Интегративные методы анализа состояний в вокальной педагогике",
    short: "Комбинирование инструментов из разных школ на уроке.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist"],
    price: "от 42 000 ₽",
  },
  {
    id: "p4",
    slug: "psihologia-tvorchestva",
    code: "№4",
    title: "Психология творчества и развитие креативности",
    short: "Как формируется творческий процесс и как его поддерживать.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist", "artist"],
    price: "от 42 000 ₽",
  },
  {
    id: "p11",
    slug: "soprovozhdenie-mutacii",
    code: "№11",
    title: "Сопровождение вокалиста в период мутации",
    short: "Работа с подростковым голосом на стыке физиологии и психологии.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist"],
    price: "от 42 000 ₽",
  },
  {
    id: "p19",
    slug: "vozrastnaya-psihologia",
    code: "№19",
    title: "Возрастная психология в вокальной педагогике",
    short: "От дошкольника до взрослого — специфика работы с каждым возрастом.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist"],
    price: "от 42 000 ₽",
  },
  {
    id: "p20",
    slug: "gruppovoe-obuchenie",
    code: "№20",
    title: "Психология группового вокального обучения",
    short: "Динамика группы, когда каждый — со своим голосом.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist"],
    price: "от 42 000 ₽",
  },
  {
    id: "p23",
    slug: "semejnye-patterny",
    code: "№23",
    title: "Семейные паттерны в вокальном обучении",
    short: "Что приходит на урок вместе с учеником из его семьи.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist", "psychologist"],
    price: "от 42 000 ₽",
  },
  {
    id: "p28",
    slug: "samoocenka-motivaciya",
    code: "№28",
    title: "Психология самооценки и мотивации",
    short: "Как ученик оценивает себя и что с этим делать педагогу.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist"],
    price: "от 42 000 ₽",
  },
  {
    id: "p29",
    slug: "chuvstva-uchenikov",
    code: "№29",
    title: "Работа с чувствами учеников",
    short: "Эмоции как материал урока, а не помеха.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist"],
    price: "от 42 000 ₽",
  },
  {
    id: "p8",
    slug: "traektoriya-vokalista",
    code: "№8",
    title: "Проектирование индивидуальной траектории вокалиста",
    short: "От первичной диагностики до долгосрочного плана развития.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist"],
    price: "от 42 000 ₽",
  },
  {
    id: "p6",
    slug: "kouchingovye-tehnologii",
    code: "№6",
    title: "Коучинговые технологии в обучении вокалу",
    short: "Формат разговора, при котором ученик находит ответ сам.",
    type: "program",
    status: "ready",
    core: "pro",
    hours: 48,
    tracks: ["vocalist"],
    price: "от 42 000 ₽",
  },

  // ─── Ядро 4. B2B ───
  {
    id: "audit",
    slug: "school-audit",
    title: "Аудит «Карта готовности вашей школы к работе с состоянием ученика»",
    short: "Самозаполняемая диагностика для руководителей студий и школ.",
    type: "sampler",
    status: "coming",
    core: "b2b",
    tracks: ["school"],
    price: "Бесплатно",
  },

  // ─── Межядерное ───
  {
    id: "mentor",
    slug: "individual-mentoring",
    title: "Индивидуальное наставничество",
    short: "Работа один-на-один с ведущим методистом ИВП.",
    type: "practicum",
    status: "ready",
    core: "cross",
    duration: "От 3 месяцев",
    tracks: ["vocalist", "psychologist", "artist"],
    price: "По запросу",
  },
];

export const readyPrograms = programs.filter((p) => p.status === "ready");
export const comingPrograms = programs.filter((p) => p.status === "coming");
export const featuredPrograms = programs.filter((p) => p.featured);

export function findProgram(slug: string): Program | undefined {
  return programs.find((p) => p.slug === slug);
}

export function byCore(core: Core): Program[] {
  return programs.filter((p) => p.core === core);
}
